import { NuqsAdapter } from 'nuqs/adapters/next/app'
import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
// import "./globals.css";
import './globals.css';
import { TRPCReactProvider } from "@/trpc/client";
import { Toaster } from "@/components/ui/sonner";


const dmSans = DM_Sans({
  subsets: ["latin"],
})
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * Root layout component that provides the global HTML structure and application-level providers.
 *
 * Wraps the page content with NuqsAdapter and TRPCReactProvider, applies the DM Sans font and antialiasing to the body, and renders a Toaster for global notifications.
 *
 * @param children - The page content to render inside the layout
 * @returns The root HTML element containing the document body and mounted providers
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body
        className={`${dmSans.className} antialiased`}
      >
        <NuqsAdapter>
        <TRPCReactProvider>
 {children}
 <Toaster />
        </TRPCReactProvider>
       </NuqsAdapter>
      </body>
    </html>
  );
}